In [19]:
from backtesting import Backtest, Strategy
import pandas as pd

In [20]:
class MeanReversionStrategy(Strategy):

    n1 = 240
    tp = 25

    def init(self):
        close_prices = self.data.Close
        self.lowest_n1 = self.I(lambda x: pd.DataFrame(x).rolling(self.n1).min(), close_prices)

    def next(self):
        low_value = self.lowest_n1[-1]
        if self.data.Close[-1] <= low_value * 1.1:
            self.buy(sl=self.data.Close[-1] * 0.8, tp=self.data.Close[-1] * ((self.tp/100)+1))

In [28]:
data = pd.read_csv("stock_market_data-AAPL.csv")
data.columns = [column.capitalize() for column in data.columns]
data = data.iloc[:-5000]
data.dropna()

      Unnamed: 0        Date     Low     High   Close     Open
0           6168  2024-05-08  181.45  183.070  182.74  182.850
1           6167  2024-05-07  181.32  184.900  182.40  183.450
2           6166  2024-05-06  180.42  184.200  181.71  182.354
3           6165  2024-05-03  182.66  187.000  183.38  186.645
4           6164  2024-05-02  170.89  173.415  173.03  172.510
...          ...         ...     ...      ...     ...      ...
1164        5004  2019-09-23  217.65  219.840  218.72  218.950
1165        5003  2019-09-20  217.47  222.560  217.73  221.380
1166        5002  2019-09-19  220.37  223.760  220.96  222.010
1167        5001  2019-09-18  219.44  222.850  222.77  221.060
1168        5000  2019-09-17  219.12  220.820  220.70  219.960

[1169 rows x 6 columns]

In [29]:
bt = Backtest(data, MeanReversionStrategy, cash=10000000)
stats = bt.optimize(maximize='Equity Final [$]', n1=range(24, 480, 10), tp=range(5,35,5))

/var/folders/ld/cmlp53c53tb76qnkpsp2t_mh0000gn/T/ipykernel_14034/4070983436.py:1: UserWarning: Data index is not datetime. Assuming simple periods, but `pd.DateTimeIndex` is advised.
  bt = Backtest(data, MeanReversionStrategy, cash=10000000)
/Users/andrewwen/Desktop/backtesting/venv/lib/python3.10/site-packages/backtesting/backtesting.py:1375: UserWarning: For multiprocessing support in `Backtest.optimize()` set multiprocessing start method to 'fork'.
  warnings.warn("For multiprocessing support in `Backtest.optimize()` "

In [30]:
stats

Start                                     0.0
End                                    1168.0
Duration                               1168.0
Exposure Time [%]                   31.907613
Equity Final [$]                 59423507.308
Equity Peak [$]                  59423507.308
Return [%]                         494.235073
Buy & Hold Return [%]               20.772682
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              0.0
Max. Drawdown [%]                  -28.367343
Avg. Drawdown [%]                   -5.132794
Max. Drawdown Duration                  219.0
Avg. Drawdown Duration              16.227273
# Trades                                  4.0
Win Rate [%]                             75.0
Best Trade [%]                     342.498464
Worst Trade [%]                    -23.272262
Avg. Trade [%]                      56.131386
Max. Trade Duration                     160.0
Avg. Trade Duration                      92.5
Profit Factor                       17.495545
Expectancy [%]                      95.972159
SQN                                  1.087299
_strategy                 MeanReversionStr...
_equity_curve                         Equi...
_trades                        Size  Entry...
dtype: object